# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='ilość')),
                ('bought', models.BooleanField(default=False, verbose_name='kupione?')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='data ostatnich zmian')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='kategoria')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='produkt')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='data ostatnich zmian')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Diet', verbose_name='dieta')),
                ('weekdays', models.ManyToManyField(to='diet.DietDay', verbose_name='dni tygodnia')),
            ],
        ),
    ]
