# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='shopping_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shopping.ShoppingList', verbose_name='lista'),
            preserve_default=False,
        ),
    ]
