# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='data ostatnich zmian')),
            ],
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątek'), ('6', 'Sobota'), ('7', 'Niedziela')], max_length=20, verbose_name='dzień tygodnia')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='data ostatnich zmian')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Diet', verbose_name='dieta')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nazwa')),
                ('time', models.TimeField(verbose_name='czas posiłku')),
                ('recipe', models.TextField(blank=True, null=True, verbose_name='przepis')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.DietDay', verbose_name='dzień diety')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='ilość')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Meal', verbose_name='posiłek')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
        ),
    ]
