# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('unit_type', models.CharField(choices=[('volume', 'Objętość'), ('mass', 'Waga')], max_length=40, verbose_name='typ jednostki')),
                ('proteins', models.FloatField(verbose_name='białko')),
                ('carbo', models.FloatField(verbose_name='węglowodany')),
                ('fat', models.FloatField(verbose_name='tłuszcze')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Category', verbose_name='kategoria')),
            ],
        ),
    ]
