# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='one_piece_amount',
            field=models.FloatField(default=1, verbose_name='ilość jednej sztuki'),
            preserve_default=False,
        ),
    ]
