# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_one_piece_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbo',
            field=models.FloatField(help_text='na 100g', verbose_name='węglowodany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(help_text='na 100g', verbose_name='tłuszcze'),
        ),
        migrations.AlterField(
            model_name='product',
            name='one_piece_amount',
            field=models.FloatField(help_text='np 150g to 1 sztuka', verbose_name='ilość jednej sztuki'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(help_text='na 100g', verbose_name='białko'),
        ),
    ]
